"""empty message

Revision ID: 62dbd1f68f6a
Revises: 
Create Date: 2022-07-03 18:06:57.834088

"""

print('Upgrading ...')
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dbd1f68f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('caption', sa.String(length=100), nullable=True, default = ''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'caption')
    # ### end Alembic commands ###
